[Details]
  Icon = "Small_Icon.png"
  Name = "Wipr"
  ID = "com.usbee.wipr"
  Version = "0.0.3"
  Build = 28

[LinuxAndBSD]
  GenericName = "Wipr"
  Categories = ["Utilities"]
  Comment = "Wipe partitions and drives"
  Keywords = ["wipe", "shred"]
