name: Build and Release

on:
  push:
    tags:
      - 'v*'

  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install MinGW-w64
        run: choco install mingw -y

      - name: Set PATH for MinGW
        run: echo "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin" >> $env:GITHUB_PATH

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Install fyne CLI
        run: go install fyne.io/tools/cmd/fyne@latest

      - name: Build
        run: fyne p

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          name: Wipr ${{github.ref_name}}
          files: Wipr.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}