name: Build and Release

on:
  push:
    tags:
      - "v*"

  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        target: [windows, linux]
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt update -y
          sudo apt-get install libgl1-mesa-dev xorg-dev libxkbcommon-dev

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Pull Docker Images
        run: docker pull fyneio/fyne-cross-images:${{ matrix.target }}

      - name: Install fyne CLI and fyne-cross
        run: |
          go install fyne.io/tools/cmd/fyne@latest
          go install github.com/fyne-io/fyne-cross@latest

      - name: Generate bundle file
        run: go generate

      - name: Build
        run: fyne-cross ${{ matrix.target }} -tags ${{ matrix.target }} -name Wipr -arch=*

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Wipr_${{ matrix.target }}
          path: fyne-cross/dist/${{ matrix.target }}-*/*

  release:
    needs: [build_windows, build_linux]
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Flatten and rename artifacts
        run: |
          mkdir renamed
          for f in $(find artifacts -type f); do base=$(basename $f); ext="${base#*.}"; archdir=$(basename $(dirname $f)); cp "$f" "renamed/Wipr_${archdir}.${ext}"; done
      
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: Wipr ${{ github.ref_name }}
          files: renamed/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}